/*2. Տրված է իրական թվերի հաջորդականություն: Արտածել YES, եթե 
 ա) դրանում դրական տարրերի քանակը ավելի մեծ է բացասական տարրերի քանակից,  
 բ) այն սիմետրիկ հաջորդականություն է,  
  գ) այն թվաբանական պրոգրեսիա է,  = nuyn hanuov 
  դ) այն երկրաչափական պրոգրեսիա է:  = vor bajanes lini naxord tiv@ 
 Հակառակ դեպքում արտածել NO*/

/* Զանգվածներ 
 1.Տրված է իրական թվերի հաջորդականություն (Մասիվ): Արտածել այդ հաջորդականության  
 ա) այն տարրերի քանակը, որոնք փոքր են իրենց կարգահամարի քառակուսուց, 
  բ) բոլոր տարրերի միջին թվաբանականի և տարրերի տարբերությունները,  
 գ) այն տարրերի քանակը, որոնք փոքր են իրենց ձախ և աջ հարևանների կիսագումարից,  
 դ) մեծագույն տարրը և նրա կարգահամարը,  
 ե) մեծագույն և փոքրագույն տարրերի տարբերությունը,  
 զ) առաջին մեծագույն և վերջին փոքրագույն տարրերի միջև գտնվող անդամների գումարը,  
 է) մեծագույն և մեծությամբ երկրորդ տարրերը,  
 ը) դրական տարրերից փոքրագույնի արժեքը (եթե դրական տարր չկա, արտածել համապատասխան հաղորդագրություն): 
 2. Տրված է իրական թվերի հաջորդականություն: Արտածել YES, եթե 
  ա) դրանում դրական տարրերի քանակը ավելի մեծ է բացասական տարրերի քանակից,  
 բ) այն սիմետրիկ հաջորդականություն է,  
  գ) այն թվաբանական պրոգրեսիա է, 
  դ) այն երկրաչափական պրոգրեսիա է:  
 Հակառակ դեպքում արտածել NO: 
 3. . Գտնել տրված իրական թվերի հաջորդականության փոքրագույն անդամը և տեղերով փոխել վերջին տարրի հետ: 
 4. Տրված է ամբողջ թվերի հաջորդականություն: Արտածել այդ հաջորդականության  
 ա) առաջին միանիշ տարրը,  
 բ) 5-ին պատիկ վերջին տարրը,  
 գ) վերջին երկնիշ տարրը և դրան հաջորդող կենտ տարրերի քանակը,  
 դ) առաջին զույգ տարրը և դրան նախորդող տարրերի գումարը, 
  ե) 7-ից մեծ վերջին տարրը և դրան նախորդող զույգ տարրերի արտադրյալը,  
 զ) մինչև առաջին բացասական տարրը եղած այն տարրերի քանակը, որոնք պատկանում են [0,20] միջակայքին,  
 է) [5,24] միջակայքում գտնվող առաջին տարրը և դրան հաջորդող տարրերի միջին թվաբանականը, 
  ը) առաջին 0-ին հաջորդող 1-ով սկսվող թվերի գումարը (եթե հաջորդականությունը 0 չի պարունակում՝ արտածել -1): 
 5.Տրված ամբողջ թվերի հաջորդականության համար արտածել, թե քանի անգամ է կրկնվում մեծագույն տարրը: 
 6. Տրված է բնական թվերի հաջորդականություն: Արտածել այդ հաջորդականության  
 ա) այն տարրերի քանակը, որոնց թվանշանների գումարը հավասար է տրված c թվին,  
 բ) 2-ի աստիճան հանդիսացող տարրերի արտադրյալը,  
 գ) որևէ թվի ֆակտորիալ հանդիսացող տարրերի միջին թվաբանականը,  
 դ) կատարյալ թվերի գումարը,  
 ե) պարզ թվերի արտադրյալը, 
  զ) Ֆիբոնաչիի թվերի քանակը,  
 է) սիմետրիկ թվերի միջին թվաբանականը,  
 ը) իրար հաջորդող սիմետրիկ թվերի ամենաերկար ենթահաջորդականության երկարությունը, թ) իրար հաջորդող տարրերի այն ամենաերկար ենթահաջորդականությունը, որի անդամների գումարը 19-ին պատիկ է, 
  ժ) իրարից տարբեր զույգ թվերի քանակը,  
 ի) այն տարրերը, որոնք որևէ բնական թվի 1-ից մեծ բնական աստիճան են:
 7. Նկարագրել ֆունկցիա, որն արգումենտում ստանում է ամբողջ թվերի հաջորդականություն և վերադարձնում է հաջորդականության  
 ա) տարրերի միջին թվաբանականը,  
 բ) ամենաշատ կրկնվող տարրը,  
 գ) այն տարրերի քանակը, որոնք առանց մնացորդի բաժանվում են իրենց կարգահամարի վրա, 
  դ) առաջին բացասական տարրի կարգահամարը կամ -1, եթե այն բացասական տարր չի պարունակում,  
 ե) վերջին 0-ի կարգահամարը կամ -1, եթե այն 0-ներ չի պարունակում*/



//    A    դրանում դրական տարրերի քանակը ավելի մեծ է բացասական տարրերի քանակից,
/*let countdrakan = 0
let countbacasakan = 0
let arrl = [5,3,9,-5,-2,3,-4,2]

for(let i = 0;i < arrl.length; i++){
    if(arrl[i] > 0){
        countdrakan++;
    }else{
        countbacasakan++
    }
}
if(countdrakan > countbacasakan){
    console.log("yes")
}else{
    console.log("no")
}*/


 //  B   այն սիմետրիկ հաջորդականություն է,  
/*let arr = [2,3,3,2]
let str = arr.join("");
let str1 = ""
for(let i = 0;i < str.length; i++){
    str1 = str[i] + str1;
}

if(str === str1){
    console.log("yes")
}else{
    console.log("no")
}*/



//     G     այն թվաբանական պրոգրեսիա է, 

/*function foo(arr){
    let d = arr[1] - arr[0];
    for(let i = 1; i <arr.lenght; i++){
        if(arr[i] - arr[i - 1] !== d){
            return "no"
        }
    }
    return "yes"
}
console.log(foo([4,6,8,10,12]))
*/





//D erkrachaakan 

 
/*function foo(arr){
    let d = arr[1] / arr[0];
    for(let i = 1; i <arr.length; i++){
        if(arr[i] / arr[i - 1] !== d){
            return "no"
        }
    }
    return "yes"
}
console.log(foo([2,4,6,8,16,32,64]))

*/
// 5in patik verjin tarr


/*let arr = [2,25,7,80,3,6,1,7]

for(let i = arr.length - 1; i >= 0 ; i--){
if(arr[i] % 5 === 0){
    console.log(arr[i])
    break;
}
}*/

// verjin erknish tarr@ ev dran hajordox kent tarreri qanak@


/*let count = 0
let index = 0
let arr = [2,25,7,80,3,6,1,7]

for(let i = arr.length - 1; i >= 0 ; i--){
    if((arr[i] >= 10 && arr[i] <= 99) || (arr[i] >= -99 && arr[i] <= -10)){
     console.log(arr[i]);
    index = i;
     break;
    } 
}

for(let i = index + 1; i < arr.length; i++){
    if(arr[i] % 2 === 1){
        count++
    }
}
console.log(count)*/




// 1i @n



/*let arr = [-3,5,-30,7,-2]
let arr1 = []
for(let i = 0; i < arr.length; i++){
    if(arr[i] > 0){
        arr1.push(arr[i])
    }
}

if(arr1.length === 0){
    console.log("drakan element chka")
    }else {
        console.log(Math.min(...arr1))
    }*/


// 1i zn 

/*let arr = [30,30,-3,-5,30,-6,-6,7,2]

let max = arr[0]
let indexmax = 0;
for(let i = 0; i < arr.length; i++){
    if(arr[i] > max){
        max = arr[i]
        indexmax = 1
    }
}
let min = arr[arr.length - 1]
let indexMin = arr.length - 1

for(let i = arr.length - 1; i >= 0; i--){
    if(arr[i] < min){
        min = arr[i];
indexMin = i
    }
}
let sum = 0
for(let i = indexmax + 1 ; i < indexMin; i++){
    sum = sum + arr[i]
}
console.log(sum)
*/




//////////////////////////////
//////////OBJECTNER//////////
////////////////////////////


// cankacac funkcia uni ira prototype
// prototype = objecta

//new Array = dardznuma array

// kanchumenq User@ ev inq@ mezi objecta sarqum u tali 


/*function User(name,age,position,addres){
    this.name = name;
    this.age = age;
    this.position = position;
    this.status = true;
    this.addres = addres;
}
let u1 = new User("Aram",30,"Programmer","Ejmiatsin","Ghexam");
console.log(u1)
*/



/*function User(name,age){
    this.name = name;
    this.age = age;
    this.admin = false;
    this.say = function(){console.log(this.name)}
}
let user1 = new User("Garik",30);
let user2 = new User("Aram",22);

console.log(user1);
console.log(user2);

user1.say()
user2.say()*/







/*let arr = [3,4,5,6,7,-9,0,5]
arr.sort((a,b) => a-b)


console.log(arr)

Array.prototype.sort = function(){console.log("barev Gurgen")}

let arr1 = []
let arr2 = [3,4,5,6,7,8]
arr1.sort()
arr2.sort()*/

////////////////////////////////////
// prototype oni menak funkcianner@
///////////////////////////////////


// ktpi array i hellon vorovhetev inq@ iran@ uni erb chlni ktpi barev keta chulanic khani 

/*let a2 = new Array(1,2,3)
console.log(a2)
Array.prototype.gugo = function(){console.log("hello")}
Object.prototype.gugo = function(){console.log("barev")}

a2.gugo()*/



// kashxati barev@ vorovhetev objectna amena karevor@

/*let str  = "a"
str.gugo();*/




//homework
//  sxala chi dzev@  378 um 
/*Object.prototype.show = function(){console.log(title,pub_year,price)}

let book1 = {
title:"programmer",
pub_year:2024,
price:"25$"
} 

let book2 = {
title:"math",
pub_year:2022,
price:"19$"
}
*/




// tvabanak prog

/*function f(arr){
    let d = arr[1] - arr[0];
for(let i = 1; i <arr.length; i++){
if(arr[i] - arr[i - 1] !== d){
return "NO"
}
}

return"YES"


}


console.log(f([2,4,6,8,10,12]))*/

// erkrachapakan   
 
/*function f(arr){
 let d = arr[1] / arr[0];
for(let i = 1; i <arr.length; i++){
if(arr[i] / arr[i - 1] !== d){
return "NO"
}
}

return"YES"


}


console.log(f([2,4,8,16,32,64]))*/

// simetrik ayne vor ajic cax caxic aj nuyn ban kardacvi  b


/*let arr = [2,2,2,3,2,2,2]
function isSimetric(arr){
    let str = arr.toString();
    let str1 = ""
    for(let i = 0;i < str.length; i++){
        str1 = str[i] + str1;
    }
    if(str === str1){
        return "yes";
    }
    return "no";
}
console.log(isSimetric([2,2,2,3,2,2,2]))
*/
 
 
 /*function f (arr){
    let count_drakan = 0;
    let count_bacasakan = 0;
    for(let i = 0; i < arr.length; i++){
        if(arr[i] < 0){
            count_bacasakan++ ;
        }else{
            count_drakan++ ;
        }
    }

if(count_drakan == count_bacasakan){
    return "havasar e"
}



    if(count_drakan > count_bacasakan){
        return "yes"
    }else{
        return"no"
    }
 }
 
 console.log(f([3,2,4,5,-4,-5]))
*/
 
 //  3 @
 
 
/*let arr =[2,4,3,2,-4,4,-35,3,3,44];
console.log(arr)
 let min = arr[0];
let index = 0;
let verj = arr[arr.length - 1] 

 for(let i = 0;i <arr.length;i++){
    if(min > arr[i]){
        min = arr[i];
        index = i;
    }
 }

 arr[arr.length - 1] = min;
 
 arr[index] = verj;
 console.log(arr)
*/      
 
 // homework uxac dzev@


/*function Book(title,pub_year,price){
this.title = title;
this.pub_year = pub_year;
this.price = price;
}
/*Book.prototype.show = function() {
    return  `${this.title}  ${this.pub_year}  ${this.price} `               
}

Book.prototype.getTitle = function(){
    return this.title
}


Book.prototype.getPrice = function() {
    return this.price
}
let book1 = new Book("JS",2024,"20$")
let book2 = new Book("Math",2022,"19$")*/

//console.log(book1)
//console.log(book2)

/*console.log(book1.getPrice())
console.log(book2.getPrice())

if(parseFloat(book1.getPrice()) > parseFloat(book2.getPrice())){
console.log(book1.getTitle())
}else{
    console.log(book2.getTitle())
}*/





// tan@ 


//  6i   gn 

/*let arr = [24,6,300,120,40,720];
let count = 0
let sum = 0
function Factorial(num){
    for(let i = 1; i <= num ; i++){
     if(num % i != 0){
       return false
     }else {
        num = num / i
     }
    }
    return true
}
for(let i = 0; i < arr.length; i++){
if(Factorial(arr[i])  === true){
    sum = sum + arr[i];
    count++
}
}
console.log(Factorial(720))*/




// katryal tiv ayn tiv ne  havasare bajararneri gumarin 
//kataryal tver 6i d

/*let arr = [24,6,300,120,40,720];
let sum = 0
for(let i = 0; i < arr.length; i++){
    if((arr[i])  === true){
        sum = sum + arr[i];
        count++
    }
    }
    console.log(sum)*/
/*
    //parz 6i e

// vor bajanvume ira vra ev meki */


    /*let arr = [1,2,3,15,5,13,11];
    let sum = 0
    for(let i = 0; i < arr.length; i++){
        if((arr[i])  === true){
            sum = sum * arr[i];
            count++
        }
        }
        console.log(sum)*/

                      
//4i d-n

/*let arr = [-8,-3,1,0,7,8,6,5,4]
let arr1 = []
let index = 0;
let sum = 0;
for(let i = 0;i < arr.length; i++ ){
    if(arr[i] % 2 === 1 || arr[i] % 2 == -1){
        arr1.push(arr[i])
    }else{
        console.log(arr[i])
        index = i;
        break;
    }
}
if(arr1.length === 0 ){
    console.log("  irenic dzax gtnvac tiv chka")
}else if( arr1.length = arr.length){
    console.log("zuyg tiv chka")
}else{
    for(let i = 0; i < arr1.length; i++){
        sum = sum + arr1[i]
    }
    console.log(sum)
}
*/


//4i en

/*let arr = [2,3,-6,5,4,5];
let arr1 = [];
let index = arr[arr.length - 1];
let res = 1;
for(let i = arr.length - 1; i >= 0; i--){
    if(arr[i] > 7){
        console.log(arr[i]);
        index = 1
        break;
    }else{
        arr1.push(arr[i]);        
    }
}
if(index === 0){
    console.log("naxordov chka")
}else if(arr1.length === arr.length){
    console.log("7 ic mec chka ")
}else {
    for(let i = 0; i < index; i++){
        res = res * arr[i]
    }
   console.log(res) 
}
 */

// 4i էն

/*let arr = [2,27,20,4,5,6,7,8];
let arr1 = [];
let sum = 0
for(let i = 0; i < arr.length; i++){
    if(arr[i] >= 5 && arr[i] <= 24){
        console.log(arr[i])
        index = i;
        break;
    }else{
        arr1.push(arr[i])
    }
}
if(arr.length === arr1.length){
    console.log("tvyal mijakayium patkanox tiv chka")
}else{
    for(let i = index + 1; i < arr.length;i++){
        sum = sum + arr[i]
    }
   let mijin = sum / (arr.length - index - 1)
   console.log(mijin) 
}*/


// ete chka tpel -1 
//4i @n

/*let arr = [4,5,6,3,0,5,2,3,123,4,5,6,11,12];
let index = -1;
let sum = 0;
let count = 0;
for(let i = 0; i < arr.length;i++){
    if(arr[i] === 0){
        index = i;
        break;
    }
}

if(index === -1 ){
    console.log(-1)
}else{
    for(let i = index + 1; i < arr.length; i++){
        let str = arr[i] + "";
        if(str[0] === "1" || (str[0] === "-" && str[1] === "1")){
         sum = sum + arr[i]
        }else{
            count++
        }
    }
    if(arr.length - index - 1 === count){
        console.log("0ic heto 1ov sksvox tiv chka")
    }else{
        console.log(sum)
    }
    console.log(sum)
}*/



// tan@ 


//  6i   gn 

/*let arr = [24,6,300,120,40,720];
let count = 0
let sum = 0
function Factorial(num){
    for(let i = 1; i <= num ; i++){
     if(num % i != 0){
       return false
     }else {
        num = num / i
     }
    }
    return true
}
for(let i = 0; i < arr.length; i++){
if(Factorial(arr[i])  === true){
    sum = sum + arr[i];
    count++
}
}
console.log(Factorial(720))*/




// katryal tiv ayn tiv ne  havasare bajararneri gumarin 
//kataryal tver 6i d

/*let arr = [24,6,300,120,40,720];
let sum = 0
for(let i = 0; i < arr.length; i++){
    if((arr[i])  === true){
        sum = sum + arr[i];
        count++
    }
    }
    console.log(sum)*/
/*
    //parz 6i e

// vor bajanvume ira vra ev meki */


    /*let arr = [1,2,3,15,5,13,11];
    let sum = 0
    for(let i = 0; i < arr.length; i++){
        if((arr[i])  === true){
            sum = sum * arr[i];
            count++
        }
        }
        console.log(sum)*/
 ////////////       
// classwork
////////////
// 6 a-n

/*let arr = [2,3,4,5,66,7,84,999,9,45];
let c = 12;
function sumDigitNumber (num){
    let sum = 0
    while(num > 0){
        sum = sum + num % 10;
        num = Math.floor(num / 10);
        
    }
    return sum;
}
let count = 0;

for(let i = 0; i < arr.length;i++){
    if(sumDigitNumber(arr[i]) === c){
        count++
    }
}
console.log(count)
*/


//6i b-n


/*let arr = [4,8,64,5,7,9,456,345];
let res = 1;

function powTwo(num){
    while(num != 1){
        if(num % 2 != 0){
            return false
        }
        num = num / 2;
    } 
    return true
}

for(let  i = 0; i < arr.length; i++){
    if(powTwo(arr[i]) === true){
        res = res * arr[i]
    }
}
console.log(res)
*/

// mijin tvab = tveri gum baj inchqan tiv ka
// 6i g-n


/*let arr = [120,24,6,23,4,5,7,90]
let count = 0;
let sum = 0

function isFactorial(num){
    if(num == 0){
        return false
    }
    let n = 1
while(num != 1){
if(num % n != 0){
    return false;
}
num = num / n;
n++
}
return true;
}


 for(let i = 0; i < arr.length; i++){
     if(isFactorial(arr[i]) === true){
         count++;
         sum = sum + arr[i]
     }
 }

console.log("mijin tvabanakan = " , sum / count)
*/

//6i d-n
/*let arr = [6,4,5,28,45,6,22,33]
let sum = 0;
function isPerfect(num){
    let sum = 0;
    for(let i = 1; i < num; i++){
        if(num % i === 0){
            sum = sum + i;
        }
    }
    if(sum == num){
        return true;
    }
    return false;
}

for(let i = 0; i < arr.length; i++){
    if(isPerfect(arr[i]) === true){
        sum = sum + arr[i]
    }
}
console.log("kataryal tveri gumar@ = " , sum)*/

 // stugum qani kataryal tiv ka minchev 100000

/*for(let i = 2; i < 100000; i++){
    if(isPerfect(i) === true){
        console.log(i)
    }
}*/


// 6i e-n


/*let arr = [17,3,4,57,23,444,56];
let res = 1;

function isSimple(num){
    for(let i = 2; i <= Math.sqrt(num); i++){
        if(num % i ===0){
            return false;
        }
    }
    return true;
}

for(let i = 0; i < arr.length; i++){
    if(isSimple(arr[i]) === true){
res = res * arr[i]
    }

}
console.group(res)

//qani tari parz tiva 1945-2060

for(let i = 1945; i < 2060; i++){
    if(isSimple(i) === true){
        console.log(i)
    }
}*/






// 7i  a-n

/*let arr = [120,25,65,78,99,9,5,];
for(let i = 0;i < arr.length; i++){
    if(arr[i] === true){
        (sum = sum + arr[i]) / 7
    }
}
console.log(arr)*/


// 6i a-n
/*let arr = [2,3,4,5,66,7,84,999,9,45]
let c = 12;

function sumDigitNumber(num){
    let sum = 0;
    while(num > 0){
        sum = sum + (num % 10);
        num = Math.floor(num  / 10);
    }
    return sum;
}

let count = 0;
for(let i = 0; i < arr.length; i++){
    if(sumDigitNumber(arr[i]) === c){
        count++
    }
}
console.log(count)
*/





// 7i g-n
/*function f(arr){
    let count = 0;
    for(let i = 0; i < arr.length; i++){
        if(arr[i] % i === 0){
            count++
        }
    }
    return count
}
console.log(f([1,2,3,12,5]))
*/



//7i d-n

/*function f(arr){
    for(let i = 0; i < arr.length; i++){
        if(arr[i] < 0){
            return i
        }
    }
    return -1
}
console.log(f([1,3,4,2,-7,3,4]));
*/


//7i e-n

/*function f(arr){
    for(let i = arr.length - 1; i >= 0; i--){
        if(arr[i] === 0){
            return i;
        }
    }
    return -1;
}

console.log(f([0,2,3,4,0,5,7]))
*/



// tnayin 
/*
V|.Արտածել տրված n թիվը չգերազանցող բոլոր այն բնական թվերը, որոնք առանց մնացորդի բաժանվում են իրենց թվանշանների գումարի վրա:

Vitali Mangasaryan, [19.05.2024 15:58]
8. Նկարագրել ֆունկցիա, որն արգումենտում ստանում է իրական թվերի զանգված և վերադարձնում է՝  
ա) true, եթե զանգվածը պարունակում է կրկնվող տարրեր, և վերադարձնում է false՝ հակառակ դեպքում,  
բ) այն տարրերի քանակը, որոնք զանգվածում հանդիպում են ճիշտ 1 անգամ:
*/


// V| xndir@

/*function sumOfDigit(n){
let sum = 0;
while(n > 0){
    sum = sum + n % 10
    n = Math.floor(n/10)
}
return sum;
}
let n = 50 
for(let i = 1; i <= n; i++){

if(i % sumOfDigit(i) === 0) {
    console.log(i);
}
}*/



// 8i a-n
/*function krknvox(arr) {
    let arr1 = [];
    for(let i = 0; i < arr.length; i++){
        if(arr1.includes(arr[i]) === false){
            arr1.push(arr[i])
        }else {
            return true
        }
    }
    return false
}
console.log(krknvox([2,3,4,5,67,4]))
*/


// 8i b-n

/*function f(arr){
    let arr1 = [];
    let obj = {};

for(let i = 0; i < arr.length; i++){
    if(obj[arr[i]] === undefined){
        obj[arr[i]] = 1;
    }else {
        obj[arr[i]]++
    }
}

for(let key in obj){
    if(obj[key] === 1){
arr1.push(key)
    }    
}
return arr1
}
console.log(f([2,3,4,5,6,12,6]))
*/

console.log(2+2)

















